### ISSUE TITLE
Payment -> Description in edit

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#59]
![Screenshot (192)](https://github.com/antonym8/Tentacle/assets/142376069/8e913d10-0909-4ab1-ae2d-3a0009dbf07c)

**Comment by M8Balaji** [comment]
Fixed @Gokilavani-m8  @Nounitha-m8

**Comment by Nounitha-m8** [comment]
@M8Balaji  @yogiofficemail  
Need to change the appropriate toast message should be displayed. Finance Categories Added Successfully, need to change it to Payment Added Successfully as well as in edit Finance Categories Updated Successfully, need to change it to Payment Updated Successfully

![Screenshot (176)](https://github.com/antonym8/Tentacle/assets/167423207/7a7cb707-0fdb-4100-bfb5-65b23ad7013d)

**Comment by M8Balaji** [comment]
@yogiofficemail 

https://tssapidemo.m8itsolutions.in/api/FinanceCategoriesList/payment
https://tssapidemo.m8itsolutions.in/api/FinanceCategoriesList/payment

**Comment by yogiofficemail** [comment]
fixed

**Comment by Gokilavani-m8** [comment]
After adding and updating a new payment name, the proper toast message has displayed. For the second time while adding and updating a new payment name, the incorrect toast message has displayed and the added payment name is not shown in the list page. Need to correct it 

[Recording-20240630_223737.webm](https://github.com/antonym8/Tentacle/assets/167422482/1b055a1f-392c-44a4-8f9a-2dc0427757a6)

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
After adding and updating a new payment name, the proper toast message has displayed. For the second time while adding and updating a new payment name, the incorrect toast message has displayed and the added payment name is not shown in the list page. Need to correct it - Not Fixed

[Recording-20240707_231418.webm](https://github.com/antonym8/Tentacle/assets/167422482/5f5bc665-7034-411a-a0e8-a3a009cd40cc)

**Comment by M8Balaji** [comment]
Fixed

**Comment by Nounitha-m8** [comment]
Pass
