### ISSUE TITLE
Allowance type -> Multiple allowance type created with same name

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#6]
![Screenshot (155)](https://github.com/antonym8/Tentacle/assets/142376069/e90c6cf3-8f8a-45b7-8f67-dbd9e9edcf16)

**Comment by Gokilavani-m8** [comment]
1. While entering already existing allowance type name, the toast message should appear as **Allowance Type Name Already Exists** not as Request failed with status code 400
2. Need to display the correct time in **Created at** field

![Screenshot (211)](https://github.com/antonym8/Tentacle/assets/167422482/699843cc-0136-426c-9af9-bc9ce6403618)

**Comment by yogiofficemail** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Not fixed

**Comment by yogiofficemail** [comment]
frontend

**Comment by M8Balaji** [comment]
{
  "name": [
    "The name has already been taken."
  ]
} Change to String @yogiofficemail

**Comment by yogiofficemail** [comment]
Fixed plz check

> { "name": [ "The name has already been taken." ] } Change to String @yogiofficemail

Tssapidemo.m8itsolutions.in url

**Comment by yogiofficemail** [comment]
![Uploading 20240703_180747.jpg…]()

**Comment by yogiofficemail** [comment]
![20240703_180747](https://github.com/antonym8/Tentacle/assets/112150339/cdd58199-87dd-411e-a693-c0afcc741207)

**Comment by Nounitha-m8** [comment]
While entering already existing allowance type name, the toast message should appear as **Allowance Type Name Already Exists** not as Request failed with status code 400 - Not fixed

![Screenshot (373)](https://github.com/antonym8/Tentacle/assets/167423207/7ad5d177-817f-4389-b476-fa1b735d6a03)

**Comment by Nounitha-m8** [comment]
Pass
